def suiji():
    import random
    import time
    a=random.randint(1,7)
    b=random.randint(1,7)
    print('>'*50)
    time.sleep(1)
    print('            稍安勿燥.......')
    time.sleep(1)
    print('            请耐心等待.......')
    time.sleep(1)
    print('            已经解决列，正在解决行!!!!!!!')
    time.sleep(1)
    print('            好了，下面即将揭晓答案！!!！！')
    time.sleep(1)
    print('            激动吗？紧张吗？刺激吗？没错就是你 上来把!')
    time.sleep(2)
    print('            本次第一个幸运星为:第%d列,第%d行'%(a,b))
    a=random.randint(1,10)
    b=random.randint(1,10)
    time.sleep(1)
    print('            本次第二个幸运星为:第%d列,第%d行'%(a,b))
    a=random.randint(1,7)
    b=random.randint(1,7)
    time.sleep(1)
    print('            本次第三个幸运星为:第%d列,第%d行'%(a,b))
    time.sleep(1)
    print('             请你们上台表演一下你们的程序!')
    print('>'*50)
    time.sleep(1)
